config/routes.rb
InfoReminder::Application.routes.draw do
  resources :groups do
    collection do 
      get :manage
    end
    resources :events
    resources :categories
  end
  match 'search/(:query)/(:page)' => 'groups#search', :as => 'search_groups'

  match 'invite(.:format)/:group_id/(:user_id)' => 'membership#invite', :as => 'invite_to_group'
  match 'confirm/join/:id/(:activation_code)' => 'membership#confirm_join', :as => 'confirm_join_group'
  match 'join/:id/(:activation_code)' => 'membership#join', :as => 'join_group'
  match 'leave/:id' => 'membership#leave', :as => 'leave_group'

  period_string = '(:year_start/:month_start/:day_start/(to/:year_end/:month_end/:day_end))'
  match 'upcoming(.:format)' => 'events#upcoming', :as => 'upcoming_events'
  match "browse/(g/:group_id)/#{period_string}" => 'events#browse', :as => 'browse_events'
  
  match 'setup/download' => 'setup#prepare', :as => 'prepare_setup'
  match 'setup/status/:id' => 'setup#status', :as => 'setup_status'
  match ':id/info-reminder-setup.exe' => 'setup#download', :as => 'download_setup'

  match 'client/:action(.:format)/(:user_id/:auth_token)' => 'client'

  match 'settings' => 'settings#show', :as => 'show_settings'
  match 'settings/:action(.:format)' => 'settings'
  devise_for :users

  root :to => 'home#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :events
  has_many :categories, :through => :group_categories
  has_many :group_categories
  has_many :users, :through => :membership, :as => :members
  has_many :memberships
  has_many :invitations
  belongs_to :user

  # Sphinx search indexes
  define_index do
    indexes :name, sortable: true
    indexes :description
    has :public, :id
  end

  GROUPS_PER_PAGE = 5

  # Finds groups which were created by user (only created by!)
  # See also find_user_groups
  def self.find_owned_user_groups(user)
    Group.where(user_id: user.id)
  end

  # Finds groups which were created by user or user has joined as member
  def self.find_user_groups(user)
    groups = Group.includes(:memberships).
    where('groups.user_id = ? OR memberships.user_id = ?', user.id, user.id)
    
  end

  # Finds user groups categorised by membership type (groups in which user is member and owner)
  def self.find_user_groups_categorised_by_membership(user)
    groups = Group.find_user_groups(user).group_by do |g|
      g.user_id == user.id ? :owner : :member 
    end
    groups[:owner] ||= Hash.new
    groups[:member] ||= Hash.new

    groups
  end

  # Finds groups which are readable for specified user
  def self.find_readable_user_groups(user)
    Group.find_user_groups(user).select do |g|
      g.user_id == user.id || g.membership(user).read || g.public
    end
  end

  def self.search_public(query, options)
    options = options || Hash.new
    options[:conditions] = { public: true }
    options[:per_page] = GROUPS_PER_PAGE
    options[:ignore_errors] = true

    Group.search(query, options)
  end

  # Returns membership object associated with user
  def membership(user)
    memberships.find do |m|
      m.user_id == user.id && !m.destroyed?
    end
  end

  # Checks whether user is owner of this group
  def is_owner?(user)
    user && self.user_id == user.id 
  end

  # Alias for is_owner?
  def is_owner(user)
    is_owner? user
  end

  # Checks whether user is member of this group
  def is_member?(user)
    user && !(m = membership(user)).nil? 
  end

  # Alias for is_member?
  def is_member(user) 
    is_member? user
  end

  # Checks whether user can read events within this group
  def can_read?(user)
    self.public || is_owner?(user) || (is_member?(user) && membership(user).read)
  end

  # alias for can_read?
  def can_read(user)
    can_read? user
  end

  # Checks whether user can write to this group
  def can_write?(user)
    is_owner?(user) || (is_member?(user) && membership(user).write)
  end

  # alias for can_write?
  def can_write(user)
    can_write? user
  end

  # Checks whether user can manage group
  def can_manage?(user)
    is_owner?(user) || (is_member?(user) && membership(user).manage)
  end

  # alias for can_manage?
  def can_manage(user)
    can_manage? user
  end

  # Checks whether user can post events within this group
  def can_post_events?(user)
    can_write? user
  end

  # alias for can_post_events?
  def can_post_events(user)
    can_post_events? user
  end

  # checks whether user can join this group
  def can_join?(user, *args) 
    options = args.first unless args.empty?
    activation_code = options[:activation_code] unless options.nil?
    (self.public || has_valid_invitation?(user, activation_code)) && membership(user).nil? && !is_owner(user)
  end

  # alias for can_join?
  def can_join(user, *args)
    can_join? user, *args
  end

  # Checks whether user can leave this group
  def can_leave?(user)
    !membership(user).nil?
  end

  def can_invite?(user)
    is_owner(user) || can_manage?(user)
  end

  # Check whether user has invitation
  def has_invitation?(user)
    invitations.any? do |u|
      u.user_id == user.id
    end
  end

  # checks whether user has valid invitation to group
  def has_valid_invitation?(user, code)
    invitations.any? do |i|
      i.user_id == user.id || (i.user_id.nil? && !code.nil? && i.activation_code == code)
    end
  end

  # alias for has_valid_invitation?
  def has_valid_invitation(user, code)
    has_valid_invitation?(user,code)
  end

  # Alias for has_invitation?
  def has_invitation(user)
    has_invitation?(user)
  end

  # Gets invitation object for user
  def invitation(user, code)
    invitations.find do |i|
      i.user_id == user.id || (!i.activation_code.nil? && i.activation_code == code)
    end
  end

  # Adds events category
  def add_category(category)
    GroupCategory.transaction do
      if category.save 
        GroupCategory.create({
          category_id: category.id,
          group_id: id
        })
      end
    end
  end

  # Adds user membership to group (Only if it's public group or user has invitation)
  def add_member(user, *args)
    options = args.first unless args.empty?
    activation_code = options[:activation_code] unless options.nil?

    if self.public || has_valid_invitation(user, activation_code) 
      i = invitation(user, activation_code).accepted = true unless !has_valid_invitation?(user, activation_code) 
      m = Membership.new_read_only({ 
        group_id: id,
        user_id: user.id
      })
      if m.save
        memberships << m
        true
      else
        false
      end
    else
      false
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!, :except => [ :search ]
  # GET /groups
  # GET /groups.json
  def search
    @query = params[:query] || ""
    @page = params[:page] || 1
    @groups = Group.search_public(@query, page: @page)

    respond_to do |format|
      format.html # index.html.erb
      format.js 
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])
    @group.user_id = current_user.id
  
    respond_to do |format|
      if @group.save
        format.html { redirect_to manage_groups_url, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to manage_groups_url, notice: 'Group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to manage_groups_url }
      format.json { head :ok }
    end
  end

  def manage
    @groups = Group.find_user_groups_categorised_by_membership(current_user)
    respond_to do |format|
      format.html 
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def invitation_url(invit)
    confirm_join_group_url invit.group, activation_code: invit.activation_code
  end

  def group_picker(groups, default)
    collection_select(:group, 
      :id, 
      groups, 
      :id, 
      :name, 
      { 
        include_blank: "All groups",
        default: default
      }) 
  end
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, 'data-tooltip' => 'Enter short name of new group i.e. UG Inf Students 2009' %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, 'data-tooltip' => 'Brief description of group i.e. Events for students of computer science on UG' %>
  </div>
 <div class="field">
    <%= f.label :public %><br />
    <%= f.check_box :public, 'data-tooltip' => 'Determines whether other users can join this group without prior invitation' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/_list.html.erb
<% groups.each do |group| %>
  <%= render :partial => 'list_element', :locals => { group: group } %>
<% end %>

app/views/groups/_list_element.html.erb
<div class="group_list_element">
  <p class="group_head">
    <%= group.name %>
  </p>
  <p class="group_details">
    <%= group.description %>
  </p>
  <p class="group_actions">
    (
    <% if group.can_read? current_user %>
      <%= link_to 'Show events', browse_events_path({ group_id: group.id }) %> |
    <% end %>
    <% if group.can_post_events? current_user %>
      <%= link_to 'New event', new_group_event_path(group) %> |
    <% end %>
    <% if group.is_owner? current_user %>
      <%= link_to 'Edit', edit_group_path(group) %> |
      <%= link_to 'Destroy', group, confirm: 'Are you sure?', method: :delete %>
    <% end %>
    <% if group.can_join? current_user %>
      <%= link_to 'Join group', confirm_join_group_path(group) %> 
    <% end %>
    <% if group.can_leave? current_user %>
      <%= link_to 'Leave group', leave_group_path(group), confirm: 'Are you sure you want to leave this group?' %>
    <% end %>
    <% if group.can_invite? current_user %>
      <%= link_to 'Invite friends', invite_to_group_path({ group_id: group}) %>
    <% end %>

    )
  </p>
</div>

app/views/groups/_search_toolbox.html.erb
<%= form_tag search_groups_path, :method => :get do |f| %>
  <%= label_tag 'query', 'Search' %>
  <%= text_field_tag 'query', @query || 'Enter your query', { id: 'search_groups_text_input' }  %>
<% end %>

app/views/groups/confirm_join.html.erb
<div class="span-24 ">
  <div id="logged_middle">
    Are you sure you want to join to group <%= @group.name %>?
    <%= link_to 'Yes, I want to join', join_group_path(@group) %>
  </div>
</div>

app/views/groups/edit.html.erb
<div id="middle-panel">
  <%= render :template => 'layouts/panel-menu' %>
  <div class="span-18 last">
    <div id="right_box_panel">
      <div id="right_box_panel_inner">
        <h1>Editing group</h1>
        <%= render 'form' %>

        <%= link_to 'Show', @group %> |
        <%= link_to 'Back', groups_path %>
      </div>
    </div>
  </div>
</div>

app/views/groups/manage.html.erb
<div id="middle-panel">
  <%= render :template => 'layouts/panel-menu' %>
  <div class="span-18 last">
    <div id="right_box_panel">
      <div id="right_box_panel_inner">
        <h1><%=t :manage_groups %></h1>
        <h3><%=t :owned_groups%></h3>
        <div class="inside_box_panel"><%= render :partial => 'list', :locals => { groups: @groups[:owner] } %> </div>
        
        <h3><%=t :member_of%></h3>
        <div class="inside_box_panel"><%= render :partial => 'list', :locals => { groups: @groups[:member] } %></div>

        <%= link_to t(:new_group), new_group_path %>
      </div>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div id="middle-panel">
  <%= render :template => 'layouts/panel-menu' %>
  <div class="span-18 last">
    <div id="right_box_panel">
      <div id="right_box_panel_inner">
        <h1>New group</h1>
        <%= render 'form' %>

        <%= link_to 'Back', groups_path %>
      </div>
    </div>
  </div>
</div>

app/views/groups/search.html.erb
<div id="middle-panel">
  <%= render :template => 'layouts/panel-menu' %>
  <div class="span-18 last">
    <div id="right_box_panel">
      <div id="right_box_panel_inner">
        <h1>Find groups</h1>
        <div id="search_groups_toolbox">
          <%= render :partial => 'search_toolbox' %>
        </div>
        <div id="search_groups_results">
          <%= render :partial => 'list', :locals => { groups: @groups } %>
        </div>
        <div id="search_pagination">
          <%= will_paginate @groups %>
        </div>
        <%= link_to 'New Group', new_group_path %>
      </div>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="span-10">
Test
</div>

<div class="span-14 last">
  <div id="logged_middle">
    <p id="notice">
      <%= notice %>
    </p>
    <p>
      <b>Name:</b>
      <%= @group.name %>
    </p>
    <p>
      <b>Description:</b>
      <%= @group.description %>
    </p>
    <p>
      <b>User:</b>
      <%= @group.user_id %>
    </p>
    <p>
      <b>Public:</b>
      <%= @group.public %>
    </p>
    <%= link_to 'New event', new_group_event_path(@group) %> |
    <%= link_to 'New event category', new_group_category_path(@group) %> |
    <%= link_to 'Show events', group_events_path(@group) %> |
    <%= link_to 'Edit', edit_group_path(@group) %> |
    <%= link_to 'Back', search_groups_path %>
  </div>
</div>