config/routes.rb
InfoReminder::Application.routes.draw do
  resources :groups do
    collection do 
      get :manage
    end
    resources :events
    resources :categories
  end
  match 'search/(:query)/(:page)' => 'groups#search', :as => 'search_groups'

  match 'invite(.:format)/:group_id/(:user_id)' => 'membership#invite', :as => 'invite_to_group'
  match 'confirm/join/:id/(:activation_code)' => 'membership#confirm_join', :as => 'confirm_join_group'
  match 'join/:id/(:activation_code)' => 'membership#join', :as => 'join_group'
  match 'leave/:id' => 'membership#leave', :as => 'leave_group'

  period_string = '(:year_start/:month_start/:day_start/(to/:year_end/:month_end/:day_end))'
  match 'upcoming(.:format)' => 'events#upcoming', :as => 'upcoming_events'
  match "browse/(g/:group_id)/#{period_string}" => 'events#browse', :as => 'browse_events'
  
  match 'setup/download' => 'setup#prepare', :as => 'prepare_setup'
  match 'setup/status/:id' => 'setup#status', :as => 'setup_status'
  match ':id/info-reminder-setup.exe' => 'setup#download', :as => 'download_setup'

  match 'client/:action(.:format)/(:user_id/:auth_token)' => 'client'

  match 'settings' => 'settings#show', :as => 'show_settings'
  match 'settings/:action(.:format)' => 'settings'
  devise_for :users

  root :to => 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :group
  belongs_to :category
  has_many :accepted_notifications

  validates_presence_of :title, :date, :group_id

  def is_owner?(user)
    self.user_id == user.id
  end

  def can_write?(user)
    is_owner?(user) || group.can_manage?(user)
  end

  def can_read?(user)
    is_owner?(user) || group.can_read?(user)
  end

  def can_delete?(user)
    is_owner?(user) || group.can_manage?(user)
  end

  def has_accepted_notification_as(user)
    !AcceptedNotification.where(event_id: self.id, user_id: user.id).first.nil?
  end

  def accept_notification_as(user)
    AcceptedNotification.create(user_id: user.id, event_id: self.id, date: Time.now)
  end

  # Returns query used to find events available to specified user
  def self.find_user_events(user) 
    groups = Group.find_readable_user_groups(user)

    group_ids = groups.map do |g|
      g.id
    end 

    Event.where(group_id: group_ids).order('date DESC') 
  end

  def self.find_user_events_within_period(user, start_date, end_date) 
    where = self.prepare_period_statement(start_date, end_date)
    query = self.find_user_events(user)

    if where.nil?
      return query
    end

    query.where(
      where, 
      { 
        start_date: start_date.midnight, 
        end_date: end_date.midnight
      }
    )
  end

  def self.find_user_events_within_period_without_accepted_notifications(user, start_date, end_date)
    accepted_event_ids = AcceptedNotification.notifications_for_user(user).map do |n|
      n.event_id
    end 
    query = self.find_user_events_within_period(user, start_date, end_date)
    if accepted_event_ids.length > 0
      query = query.where('events.id NOT IN (?)', accepted_event_ids)
    end

    query
  end


  private

  def self.prepare_period_statement(start_date, end_date)
    if !start_date.nil?
      query = "events.date >= :start_date"
    end

    if !end_date.nil?
      query = !query.nil? ? "#{query} AND " : ""
      query += "events.date <= :end_date"
    end

    query
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :fetch_group 
  before_filter :authenticate_user!

  def upcoming 
    @events = current_user.upcoming_events 

    respond_to do |format|
      format.html
      format.json { render json: @events }
    end
  end

  # GET /events
  # GET /events.json
  def browse
    @period = get_period_from_params
    @events = Event.find_user_events_within_period(
      current_user,
      @period[:start_date],
      @period[:end_date]
    ) 

    unless params[:group_id].nil?
      @events = @events.where(group_id: params[:group_id])
    end

    respond_to do |format|
      format.html { render 'browse', :locals => { events: @events } }
      format.js  
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = @group.events.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to browse_events_path(group_id: @event.group_id), notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to manage_groups_url, notice: 'Event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to [@event.group, @event]}
      format.json { head :ok }
    end
  end
  
  private
  def get_period_from_params
    period = Hash.new

    if has_start_date?
      period[:start_date] = get_date_from_params "start"
    end

    if has_end_date?
      period[:end_date] = get_date_from_params "end"
    end

    period
  end

  def get_date_from_params(name)
    if has_date?(name)
      has_partial_date(name) ? get_date_from_parts(name) : get_date_from_single_param(name)
    else
      nil
    end
  end

  def get_date_from_single_param(name)
    Time.parse params["date_#{name}"]
  end

  def get_date_from_parts(name)
   Time.new(
        params["year_#{name}"],
        params["month_#{name}"],
        params["day_#{name}"]
      )
  end

  def has_partial_date(name)
    (!params["year_#{name}"].nil? && !params["month_#{name}"].nil? && !params["day_#{name}"].nil?) 
  end

  def has_single_date(name)
    !params["date_#{name}"].nil?
  end

  def has_date?(name)
    has_partial_date(name) || has_single_date(name)
  end

  def has_start_date?
    has_date? "start"
  end

  def has_end_date?
    has_date? "end"
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def date_picker(name, date)
    date = date.nil? ? Time.now : date 
    date_str = date.strftime("%F")
    picker_class = 'datepicker'

    label_tag(t(name)) + text_field_tag(name, date_str, :class => picker_class)
  end
end

app/views/events/_calendar.html.erb
<div id="browse_ui">
  <%= form_tag browse_events_path, :id => 'browse_events_form' do %>
    <div class="field">
      <%= label_tag(t(:group)) %>
      <%= group_picker current_user.readable_groups, params[:group_id] %>
    </div>
    <div class="field">
      <%= date_picker("date_start", @period[:start_date]) %>
    </div>
    <div class="field">
      <%= date_picker("date_end", @period[:end_date]) %>
    </div>
    <div class="actions">
      <%= submit_tag "Filter" %>
    </div>
  <% end %>
</div>

app/views/events/_event.html.erb
<p class="event_title">
  <%= event.title %>
  <span class="event_date">
    <%= event.date %>
  </span>
</p>
<div class="event_content">
<%= event.description %>
</div>

app/views/events/_form.html.erb
<%= form_for([@group, @event]) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, 'data-tooltip' => 'Short name of event i.e. Math Exam' %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :category %>
    <%= f.collection_select(:category_id, @group.categories, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date, :class => 'datepicker', 'data-tooltip' => 'Date when this event occurs' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_list.html.erb
<div id="event_list">
  <%= render :partial => 'list_element', :collection => events, :as => 'event' %>
</div>

app/views/events/_list_element.html.erb
<div class="event_list_element">
  <p class="event_head">
    <%= event.title %>
    <span>
      <%= event.date %>
    <span>
  </p>
  <p class="event_details">
    <%= event.description %>
  </p>
  <p class="event_tail">
    within group <%= link_to event.group.name, browse_events_path(group_id: event.group.id) %>
  </p>
</div>

app/views/events/all.html.erb
<h1>My events</h1>

<%= render :partial => 'event', :collection => @events %>

app/views/events/browse.html.erb
<div id="middle-panel">
  <%= render :template => 'layouts/panel-menu' %>
  <div class="span-18 last">
    <div id="right_box_panel">
      <div id="right_box_panel_inner">
        <h1><%= t :event_browser %></h1>
        <div id="event_calendar">
          <%= render :partial => 'calendar' %>
        </div>
        <div id="event-left">
        <%= render :partial => 'list', :locals => { events: events } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/browse.js.erb
Events.EventList.hide();
Events.EventList.clear();
<% @events.each do |e| %>
Events.EventList.add("<%=j render :partial => 'list_element', :locals => { event: e } %>");
<% end %>
Events.EventList.show();

app/views/events/edit.html.erb
<div class="span-24 ">
  <div id="logged_middle">
    <div id="logged_middle_inner">
      <h1><%=t :editing_event %></h1>
      <%= render 'form' %>

      <%= link_to t(:show), group_event_path(@event.group_id, @event.id) %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="span-24 ">
  <div id="logged_middle">
    <div id="logged_middle_inner">
      <h1><%=t :listing_events %></h1>
      <table>
        <tr>
          <th><%=t :title %></th>
          <th><%=t :description %></th>
          <th><%=t :date %></th>
          <th><%=t :group %></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        <% @events.each do |event| %>
        <tr>
          <td><%= event.title %></td>
          <td><%= event.description %></td>
          <td><%= event.date %></td>
          <td><%= event.group %></td>
          <td><%= link_to t(:show), group_event_path(event.group_id, event.id) %></td>
          <td><%= link_to t(:edit), edit_group_event_path(event.group.id, event.id) %></td>
          <td><%= link_to t(:destroy), group_event_path(event.group_id, event.id), confirm: 'Are you sure?', method: :delete %></td>
        </tr>
        <% end %>
      </table>
      <br />
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div id="middle-panel">
  <%= render :template => 'layouts/panel-menu' %>
  <div class="span-18 last">
    <div id="right_box_panel">
      <div id="right_box_panel_inner">
        <h1><%=t :new_event %></h1>
        <%= render 'form' %>

        <%= link_to t(:back), group_events_path %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="span-24 ">
  <div id="logged_middle">
    <div id="logged_middle_inner">
      <p id="notice">
        <%= notice %>
      </p>
      <p>
        <b><%=t :title %></b>
        <%= @event.title %>
      </p>
      <p>
        <b><%=t :description %></b>
        <%= @event.description %>
      </p>
      <p>
        <b><%=t :date %></b>
        <%= @event.date %>
      </p>
      <p>
        <b><%=t :group %></b>
        <%= @event.group %>
      </p>
      <%= link_to t(: edit), edit_group_event_path(@event.group_id, @event.id) %>
    </div>
  </div>
</div>

app/views/events/upcoming.html.erb
<div id="middle-panel">
  <%= render :template => 'layouts/panel-menu' %>
  <div class="span-18 last">
    <div id="right_box_panel">
      <div id="right_box_panel_inner">
        <h1><%= t :upcoming_events %></h1>
        <%= render :partial => 'list', :locals => { events: @events } %>
      </div>
    </div>
  </div>
</div>