config/routes.rb
InfoReminder::Application.routes.draw do
  resources :groups do
    collection do 
      get :manage
    end
    resources :events
    resources :categories
  end
  match 'search/(:query)/(:page)' => 'groups#search', :as => 'search_groups'

  match 'invite(.:format)/:group_id/(:user_id)' => 'membership#invite', :as => 'invite_to_group'
  match 'confirm/join/:id/(:activation_code)' => 'membership#confirm_join', :as => 'confirm_join_group'
  match 'join/:id/(:activation_code)' => 'membership#join', :as => 'join_group'
  match 'leave/:id' => 'membership#leave', :as => 'leave_group'

  period_string = '(:year_start/:month_start/:day_start/(to/:year_end/:month_end/:day_end))'
  match 'upcoming(.:format)' => 'events#upcoming', :as => 'upcoming_events'
  match "browse/(g/:group_id)/#{period_string}" => 'events#browse', :as => 'browse_events'
  
  match 'setup/download' => 'setup#prepare', :as => 'prepare_setup'
  match 'setup/status/:id' => 'setup#status', :as => 'setup_status'
  match ':id/info-reminder-setup.exe' => 'setup#download', :as => 'download_setup'

  match 'client/:action(.:format)/(:user_id/:auth_token)' => 'client'

  match 'settings' => 'settings#show', :as => 'show_settings'
  match 'settings/:action(.:format)' => 'settings'
  devise_for :users

  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InfoReminder</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="loading_bar"><%=t :page_load_info %></div>
    <div class="container">
      <div class="span-24">
        <div id="header">
          <%= link_to 'infoReminder', root_url, :id=>'title_logo' %>
          <div id="top_menu">
            <div id="user_menu">
              <% if user_signed_in? %>
              <%= render partial: 'users/signed_in_menu' %>

              <% else %>
              <%= render partial: 'users/signed_out_menu' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div id="content">
        <%= yield %>
      </div>
      <div class="span-24">
        <div id="footer_bar">
          Copyright 2012 infoReminder Apps Inc.
        </div>
      </div>
  </body>
</html>

app/views/layouts/informational.html.erb
<div id="middle">
  <div class="span-16 ">
    <div id="showcase" class="showcase" style="padding-top: 20px;">
    <!-- Each child div in #showcase represents a slide -->
    <div class="showcase-slide">
        <div class="showcase-content">
            <div class="showcase-content-wrapper">
                <%= image_tag("slider1.jpg", :alt => "01")	 %>
            </div>
        </div>
    </div>
    <div class="showcase-slide">
        <div class="showcase-content">
            <div class="showcase-content-wrapper">
                <%= image_tag("slider2.jpg", :alt => "02")	 %>
            </div>
        </div>
    </div>
     <div class="showcase-slide">
        <div class="showcase-content">
            <div class="showcase-content-wrapper">
                <%= image_tag("slider3.jpg", :alt => "03")	 %>
            </div>
        </div>
    </div>
     <div class="showcase-slide">
        <div class="showcase-content">
            <div class="showcase-content-wrapper">
                <%= image_tag("slider4.jpg", :alt => "04")	 %>
            </div>
        </div>
    </div>
</div>
  </div>
  <div class="span-8 last">
    <div id="right_box">
      <%= yield(:content) %>
    </div>
  </div>
</div>
<%= render 'home/tips_bar' %> 

app/views/layouts/panel-menu.html.erb
<div class="span-6 ">
  <div id="left-menu">
    <div id="menu_links">
      <div class="menu_title">
        Menu
      </div>
      <%= link_to t(:find_groups), search_groups_path %>
      <%= link_to t(:manage_groups), manage_groups_path %>
      <%= link_to t(:upcoming_events), upcoming_events_path %>
      <%= link_to t(:browse_events), browse_events_path %>
    </div>
  </div>
</div>